name: minesort
version: 0.4.0
main: com.johanneshardt.minesort.Plugin
description: A plugin to allow players on a paper server to sort their inventories or chests in the world.
author: johanneshardt
api-version: '1.21.4'
load: POSTWORLD