name: Create release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build fat jar with Shadow
        run: ./gradlew shadowJar

      - name: Publish jar to release
        run: gh release create ${{ github.ref_name }} app/build/libs/minesort-*.jar --generate-notes --fail-on-no-commits
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
